
<table class="example">
  <tr>
    <th style="margin-left: 1em;min-width: 11em;border: 1px solid black;"> Plain form </th>
    <th style="margin-left: 1em;min-width: 11em;border: 1px solid black;"> Honorific </th>
    <th style="margin-left: 1em;min-width: 11em;border: 1px solid black;"> Humble </th>
  </tr>
  <tr>
    <td> @HI{{suru}} </td>
    <td> @HI{{nasaru}} </td>
    <td title="@HI{{itasu}}"> @KJ{{doth}}@HI{{su}} </td>
  </tr>
  <tr>
    <td title="@HI{{iku}}"> @KJ{{going}}@HI{{ku}} </td>
    <td>  @HI{{irassharu}}/@HI{{oideninaru}}</td>
    <td title="@HI{{mairu}}">  @KJ{{nonplussed}}@HI{{ru}} </td>
  </tr>
  <tr>
    <td title="@HI{{kuru}}"> @KJ{{come}}@HI{{ru}} </td>
    <td>  @HI{{irassharu}}/@HI{{oideninaru}}</td>
    <td title="@HI{{mairu}}">  @KJ{{nonplussed}}@HI{{ru}} </td>
  </tr>
  <tr>
    <td> @HI{{iru}} </td>
    <td> @HI{{irassharu}}/@HI{{oideninaru}}</td>
    <td> @HI{{oru}} </td>
  </tr>
  <tr>
    <td title="@HI{{miru}}"> @KJ{{see}}@HI{{ru}} </td>
    <td title="@HI{{gorannninaru}}"> @HI{{go@KJ{{perusal}}ninaru}} </td>
    <td title="@HI{{haikenn}}"> @KJ{{worship^see}}@HI{{suru}} </td>
  </tr>
  <tr>
    <td> @KJ{{hear}}@HI{{ku}} </td>
    <td> - </td>
    <td title="@HI{{ukagau}}"> @KJ{{pay*respects}}@HI{{u}} </td>
  </tr>
  <tr>
    <td title="@HI{{iu}}"> @KJ{{say}}@HI{{u}} </td>
    <td> @HI{{osharu}} </td>
    <td>
      <span class="normal" title="@HI{{mousu}}"> @KJ{{speaketh}}@HI{{su}} </span> /
      <span class="normal" title="@HI{{moushiageru}}"> @HI{{@KJ{{speaketh}}shi@KJ{{above}}geru}} </span>
    </td>
  </tr>
  <tr>
    <td> @HI{{ageru}} </td>
    <td> - </td>
    <td title="@HI{{sashiageru}}"> @HI{{@KJ{{distinction}}shi@KJ{{above}}geru}} </td>
  </tr>
  <tr>
    <td> @HI{{kureru}} </td>
    <td title="@HI{{kudasaru}}"> @KJ{{below}}@HI{{saru}} </td>
    <td> - </td>
  </tr>
  <tr>
    <td> @HI{{morau}} </td>
    <td> -  </td>
    <td> @HI{{itadaku}} </td>
  </tr>
  <tr>
    <td title="@HI{{taberu}}"> @HI{{eat}}@HI{{beru}} </td>
    <td title="@HI{{meshiagaru}}"> @HI{{@KJ{{seduce}}shi@KJ{{above}}garu}} </td>
    <td> @HI{{itadaku}} </td>
  </tr>
  <tr>
    <td title="@HI{{nomu}}"> @KJ{{drink}}@HI{{mu}} </td>
    <td title="@HI{{meshiagaru}}"> @HI{{@KJ{{seduce}}shi@KJ{{above}}garu}} </td>
    <td> @HI{{itadaku}} </td>
  </tr>
  <tr>
    <td title="@HI{{shiteiru}}"> @KJ{{know}}@HI{{tteiru}} </td>
    <td title="@HI{{gozonji}}"> @HI{{go@KJ{{exist^know}}}} (@HI{{desu}}) </td>
    <td title="@HI{{zonjiru}}"> @HI{{@KJ{{exist}}jiru}}</td>
  </tr>
  <tr>
    <td title="@HI{{au}}"> @KJ{{meeting}}@HI{{u}} </td>
    <td> - </td>
    <td> @HI{{omeni oru}} </td>
  </tr>
</table>
