JHTML_SRCS += aap.jhtml
JHTML_SRCS += ahij-vocabulary.jhtml
JHTML_SRCS += doajg.jhtml
JHTML_SRCS += dobjg.jhtml
JHTML_SRCS += doijg.jhtml
JHTML_SRCS += jpod-absolute-beginner.jhtml
JHTML_SRCS += jpod-advanced.jhtml
JHTML_SRCS += jpod-beginner.jhtml
JHTML_SRCS += jpod-intermediate.jhtml
JHTML_SRCS += jpod-lower-intermediate.jhtml
JHTML_SRCS += jpod-miscellaneous.jhtml
JHTML_SRCS += jpod-upper-intermediate.jhtml
JHTML_SRCS += jpod.jhtml
JHTML_SRCS += kic.jhtml
JHTML_SRCS += kzm-n2g.jhtml
JHTML_SRCS += kzm-n3g.jhtml
JHTML_SRCS += kzm-n3g-exercises.jhtml
JHTML_SRCS += mnn-int.jhtml
JHTML_SRCS += mnn.jhtml
JHTML_SRCS += nsm-n2g.jhtml
JHTML_SRCS += nsm-n3g.jhtml
JHTML_SRCS += study-material.jhtml

TARGETS += $(foreach JH,$(JHTML_SRCS),$(OUTPUT)/$(subst .jhtml,.html,$(JH))) 

include $(MAKERULESDIR)/lib.make
